[package]
name = "timetable-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
druid = { version = "0.8.2", features = ["im"] }
uuid = { version = "1.3.0", features = ["v4"] }
